apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres-label
  ports:
  - port: 5432
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: bmV3X3B3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels: 
      app: postgres-label
  template:
    metadata:
      name: postgres
      labels:
        app: postgres-label
    spec:
      containers:
      - name: postgres-container
        image: postgres:9.6
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_USER
          valueFrom: 
            secretKeyRef:
              name: postgres-secrets
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: postgres-secrets
              key: password