apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: vote-pod
    app: vote-label
  name: vote-pod
spec:
  containers:
  - env:
    - name: REDIS_HOST
      value: redis-service
    image: gcr.io/cloudogu-trainings/orpheus/vote:0.2
    name: vote-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
