apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  labels:
    app: vote-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vote-deployment
  template:
    metadata:
      name: vote-deployment
      labels:
        app: vote-deployment
    spec:
      containers:
        - name: vote-pod
          image: gcr.io/cloudogu-trainings/orpheus/vote:0.2
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: "redis-service"
